// Generated by tools/generate_stage2.py; edit or regenerate before play.
export const STAGE2_DATA = {
  "width": 4,
  "startX": 18,
  "scrollSpeed": 3,
  "bossDistance": 200,
  "sections": [
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -7.37,
      "top": 7.563
    },
    {
      "bottom": -6.563,
      "top": 7.28
    },
    {
      "bottom": -5.639,
      "top": 7.068
    },
    {
      "bottom": -4.681,
      "top": 6.833
    },
    {
      "bottom": -3.759,
      "top": 6.5
    },
    {
      "bottom": -2.907,
      "top": 6.043
    },
    {
      "bottom": -2.119,
      "top": 5.486
    },
    {
      "bottom": -1.359,
      "top": 4.889
    },
    {
      "bottom": -1.418,
      "top": 4.724
    },
    {
      "bottom": -1.466,
      "top": 4.635
    },
    {
      "bottom": -1.55,
      "top": 4.575
    },
    {
      "bottom": -1.737,
      "top": 4.477
    },
    {
      "bottom": -2.089,
      "top": 4.27
    },
    {
      "bottom": -2.635,
      "top": 3.91
    },
    {
      "bottom": -3.357,
      "top": 3.399
    },
    {
      "bottom": -4.185,
      "top": 2.786
    },
    {
      "bottom": -5.012,
      "top": 2.158
    },
    {
      "bottom": -5.717,
      "top": 1.617
    },
    {
      "bottom": -6.198,
      "top": 1.248
    },
    {
      "bottom": -6.397,
      "top": 1.1
    },
    {
      "bottom": -6.312,
      "top": 1.17
    },
    {
      "bottom": -5.995,
      "top": 1.406
    },
    {
      "bottom": -5.536,
      "top": 1.728
    },
    {
      "bottom": -5.031,
      "top": 2.05
    },
    {
      "bottom": -4.562,
      "top": 2.31
    },
    {
      "bottom": -4.168,
      "top": 2.488
    },
    {
      "bottom": -3.845,
      "top": 2.61
    },
    {
      "bottom": -3.55,
      "top": 2.735
    },
    {
      "bottom": -3.227,
      "top": 2.939
    },
    {
      "bottom": -2.828,
      "top": 3.277
    },
    {
      "bottom": -2.342,
      "top": 3.77
    },
    {
      "bottom": -1.799,
      "top": 4.385
    },
    {
      "bottom": -1.271,
      "top": 5.044
    },
    {
      "bottom": -0.852,
      "top": 5.64
    },
    {
      "bottom": -1.859,
      "top": 6.39
    },
    {
      "bottom": -3.11,
      "top": 6.833
    },
    {
      "bottom": -4.481,
      "top": 7.079
    },
    {
      "bottom": -5.824,
      "top": 7.274
    },
    {
      "bottom": -7.018,
      "top": 7.552
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    },
    {
      "bottom": -8.0,
      "top": 8.0
    }
  ],
  "turrets": [
    {
      "section": 8,
      "side": "bottom"
    },
    {
      "section": 11,
      "side": "top"
    },
    {
      "section": 14,
      "side": "bottom"
    },
    {
      "section": 17,
      "side": "top"
    },
    {
      "section": 20,
      "side": "bottom"
    },
    {
      "section": 23,
      "side": "top"
    },
    {
      "section": 26,
      "side": "bottom"
    },
    {
      "section": 29,
      "side": "top"
    },
    {
      "section": 32,
      "side": "bottom"
    }
  ]
};
