"""Generate and validate the stored Stage 2 corridor. No runtime randomness."""
import json
import math
from pathlib import Path

sections = []
for i in range(64):
    center = 2.3 * math.sin(i * .22) + .5 * math.sin(i * .57)
    half_gap = 3.4 + .35 * math.cos(i * .31)
    opening = max(0, 1 - i / 8)
    arena = min(1, max(0, (i - 34) / 6))
    center *= (1 - opening) * (1 - arena)
    half_gap += (8 - half_gap) * max(opening, arena)
    sections.append({"bottom": round(center - half_gap, 3), "top": round(center + half_gap, 3)})

# Expanded walls must leave overlapping safe intervals and an achievable center path.
for i, section in enumerate(sections):
    assert section["top"] - section["bottom"] >= 6
    assert -8 <= section["bottom"] < section["top"] <= 8
    if i:
        previous = sections[i - 1]
        assert max(section["bottom"], previous["bottom"]) + .8 < min(section["top"], previous["top"]) - .8
        delta = abs((section["top"] + section["bottom"] - previous["top"] - previous["bottom"]) / 2)
        assert delta < 10 * 4 / 3 * .25

turrets = [{"section": i, "side": "bottom" if n % 2 == 0 else "top"}
           for n, i in enumerate(range(8, 35, 3))]
data = {"width": 4, "startX": 18, "scrollSpeed": 3, "bossDistance": 200,
        "sections": sections, "turrets": turrets}
target = Path(__file__).resolve().parents[1] / "stage2Data.js"
target.write_text("// Generated by tools/generate_stage2.py; edit or regenerate before play.\n"
                  "export const STAGE2_DATA = " + json.dumps(data, indent=2) + ";\n", encoding="utf-8")
print(f"Validated {len(sections)} corridor sections and {len(turrets)} turret placements.")
